### ISSUE TITLE
[QUESTION] Layer with no bias while prunning?

### ISSUE THREAD

**Issue by franferraz98** [nathanhubens/fasterai#9]
Hello again,

Continuing the example from my last issue (I'm trying to compress a resnet18 vision_learner model by following the Get Started tutorial), when performing the following operation:

```python
# Launch training
teacher.fine_tune(epochs)

# Distill
m = globals()[config["model"]] # resnet18()
student = Learner(data_loaders, m(num_classes=int(teacher.n_out)),
                  metrics=[accuracy])
kd_cb = KnowledgeDistillationCallback(teacher.model, SoftTarget)
student.fit_one_cycle(epochs, 1e-4, cbs=kd_cb)

# Sparsify
sp_cb = SparsifyCallback(sparsity=50, granularity='filter',
                         context='global', criteria=large_final,
                         schedule=cos)
student.fit(5, 1e-5, cbs=sp_cb)

# Prune
pruner = Pruner()
pruned_model = pruner.prune_model(student.model)

```
I'm encountering the following error.

```bash
 File "/home/deeplearning/workspace/refactor/src/pipeline/training/training_classification.py", line 66, in train
    pruned_model = pruner.prune_model(student.model)
  File "/home/deeplearning/workspace/refactor/.venv/lib/python3.9/site-packages/fasterai/sparse/pruner.py", line 135, in prune_model
    new_m, new_next_m = self.prune_conv(m, layers[layer_names[next_conv_ix]]) # Prune the current conv layer
  File "/home/deeplearning/workspace/refactor/.venv/lib/python3.9/site-packages/fasterai/sparse/pruner.py", line 32, in prune_conv
    new_weights, new_biases, new_next_weights = self.filters_to_keep(layer, nxt_layer)
  File "/home/deeplearning/workspace/refactor/.venv/lib/python3.9/site-packages/fasterai/sparse/pruner.py", line 23, in filters_to_keep
    biases_keep = layer.bias.index_select(0, ixs[0]).data
AttributeError: 'NoneType' object has no attribute 'index_select'
```
Could you please give me a hand?

**Comment by nathanhubens** [comment]
Hey @franferraz98 , 

Actually the `Pruner`is not yet available for networks that have residual connections, as stated on top of [this doc page](https://nathanhubens.github.io/fasterai/sparse.pruner.html). This is actually very difficult to implement as the physical removal of filters is architecture dependent. 

I am however currently working on a general solution that will allow to do so, I don't have ETA but I hope that it will be released soon, so stay tuned 😊

**Comment by franferraz98** [comment]
Hi @nathanhubens,

Totally missed the warning when reading, sorry. Then I can benefit from Batch Normalization and FC Layers Factorization even without pruning, right?

Also, is it possible to apply mixed precission training / quantization to a FastAI model? Can you point me to any guide on how to do that?

Thanks a lot!

**Comment by nathanhubens** [comment]
Hey @franferraz98 , 

Yes Batch Norm Folding and FC Factorization should both work for your model.

For Mixed Precision [here is the guide](https://docs.fast.ai/callback.fp16.html). Basically, appending `.to_fp16()` to your learner should be enough to enable it.

Have a great day

**Comment by franferraz98** [comment]
Hi @nathanhubens,

Perfect, thanks for everything. Keep up the good work sir, I'm closing now.
